#!/bin/sh

usage () {
    echo "$0 [filename]"
    echo "filename \t- this pdf file will be OCRed"
}

if [ $# -ne 1 ] ; then
    usage
    exit 1
fi

file="/tmp/input/$1"

if [ ! -e $file ] ; then
    echo "\"$1\" does not exist. At the moment only relative paths supported."
    exit 1
fi

oldfile=$(echo $1 | sed 's/\(.*\)\.\([Pp][Dd][Ff]\)/\1_copy.\2/g')

if [ -e $oldfile ] ; then
    echo "Copy of file already exists \"$oldfile\""
    echo "Abort"
    exit 1
fi

mv $file $oldfile

ocrmypdf -l deu --deskew --remove-background --clean-final --optimize 3 "$oldfile" "$file"
exitcode=$?

if [ $exitcode -eq 6 ]
then
    mv $oldfile $file
    echo "Already OCRd just copy!"
else
    echo "Exit Code: $exitcode"
    echo "Failed to process $file"
fi
